package main

import (
	"fmt"

	"github.com/go-gota/gota/dataframe"
)

//CleanCSV cleans the CSV generated by TransformToCSV
func CleanCSV(header *[]string, records *[][]string) error {
	//load data
	data := [][]string{*header}
	data = append(data, *records...)

	df := dataframe.LoadRecords(data)

	fmt.Println(df)

	return nil
}
